[project]
name = "FSI_PROJECT"
version = "0.1.0"
requires-python = ">=3.10"
dependecies = [
    "fastapi",
    "uvicorn",
    "python-multipart",
    "pydantic-settings",
    "langchain",
    "langchain-huggingface",
    "langchain-qdrant",
    "llama-parse",
    "qdrant-client"
]
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-qdrant>=1.1.0",
    "llama-parse>=0.6.94",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "qdrant-client>=1.19.1",
    "requests>=2.34.2",
    "sentence-transformers>=6.1.0",
    "streamlit>=1.64.0",
    "uvicorn>=0.53.0",
]
